#!/bin/bash
# Helper script to display Render environment variable values

echo "=========================================="
echo "Render Environment Variables Setup"
echo "=========================================="
echo ""
echo "After deploying on Render, use these values:"
echo ""
echo "--- BACKEND SERVICE ---"
echo "DEEPSEEK_API_KEY=YOUR-DEEPSEEK-API-KEY-HERE"
echo ""
echo "ALLOWED_ORIGINS=https://YOUR-FRONTEND-URL.onrender.com"
echo "  (Replace YOUR-FRONTEND-URL with your actual frontend service URL)"
echo ""
echo "--- FRONTEND SERVICE ---"
echo "REACT_APP_API_URL=https://YOUR-BACKEND-URL.onrender.com"
echo "  (Replace YOUR-BACKEND-URL with your actual backend service URL)"
echo ""
echo "=========================================="
echo ""
echo "Steps:"
echo "1. Deploy services on Render"
echo "2. Note your backend URL from Render dashboard"
echo "3. Note your frontend URL from Render dashboard"
echo "4. Set ALLOWED_ORIGINS = your frontend URL"
echo "5. Set REACT_APP_API_URL = your backend URL"
echo "6. Set DEEPSEEK_API_KEY = YOUR-DEEPSEEK-API-KEY (get from https://platform.deepseek.com)"
echo "7. Redeploy both services"
echo ""

